version: '3'

networks:
  main:
    driver: bridge


services:
  server1:
    build:
      context: ./echo-server
    environment:
      SERVER_NAME: "Server A"
      PORT: 3000
    networks:
      - main
    expose:
      - 3000
  server2:
    build: 
      context: ./echo-server
    environment:
      SERVER_NAME: "Server B"
      PORT: 3000
    expose:
      - 3000
    networks:
      - main
  reverse-proxy:
    image: nginx:latest
    networks:
      - main
    ports:
      - "80:8080"
    volumes:
      - ./default.conf:/etc/nginx/nginx.conf